create table app_user (
  id integer primary key generated by default as identity,
  _role smallint,
  username varchar not null,
  password_hash varchar not null,
  first_name varchar,
  last_name varchar,
  mobile varchar,
  email varchar,
  registered_at timestamp,
  last_login timestamp
);

create table category (
  id integer primary key generated by default as identity,
  title varchar,
  meta_title varchar,
  content varchar
);

create table product_category (
  id_category integer not null,
  id_product integer not null
);

create table product (
  id integer primary key generated by default as identity,
  title varchar,
  summary varchar,
  created_at timestamp default now(),
  updated_at timestamp,
  content text
);

create table item (
  id integer primary key generated by default as identity,
  id_product integer not null,
  id_supplier integer not null,
  id_order integer not null,
  sku varchar,
  mrp float,
  discount float not null default 0.0,
  price float not null default 0.0,
  quantity integer not null default 0,
  sold integer not null default 0,
  available integer not null default 0,
  defective integer not null default 0,
  created_by integer not null,
  updated_by integer,
  created_at timestamp not null default now(),
  updated_at timestamp,
  content text
);

create table order (
  id integer primary key generated by default as identity,
  id_user integer not null,
  "type" smallint not null,
  sub_total float not null,
  item_discount float not null default 0.0,
  tax float not null default 0.0,
  shipping float not null default 0.0,
  total float not null default 0.0,
  promo varchar,
  discount float not null default 0.0,
  grand_total float not null,
  created_at timestamp not null default now(),
  updated_at timestamp,
  content text
);

create table order_item (
  id integer primary key generated by default as identity,
  id_product integer not null,
  id_item integer not null
);